### ISSUE TITLE
Invalid query leads to exception

### ISSUE THREAD

**Issue by jeffmaury** [mthmulders/mcs#51]
I entered:

mcs search :quarkus-parent

and got:
```

Searching for :quarkus-parent...
Error parsing search response: Unrecognized token 'Solr': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 6]
java.io.UncheckedIOException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Solr': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 6]
        at it.mulders.mcs.common.SearchResponseBodyHandler.lambda$toSupplierOfSearchResponse$0(SearchResponseBodyHandler.java:36)
        at it.mulders.mcs.search.SearchClient.performSearch(SearchClient.java:77)
        at it.mulders.mcs.search.SearchClient.singularSearch(SearchClient.java:49)
        at it.mulders.mcs.search.SearchCommandHandler.performCoordinateSearch(SearchCommandHandler.java:52)
        at it.mulders.mcs.search.SearchCommandHandler.search(SearchCommandHandler.java:21)
        at it.mulders.mcs.cli.Cli$SearchCommand.call(Cli.java:49)
        at it.mulders.mcs.cli.Cli$SearchCommand.call(Cli.java:32)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at it.mulders.mcs.App.doMain(App.java:17)
        at it.mulders.mcs.App.main(App.java:10)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Solr': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 6]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:2391)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:745)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3634)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2734)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:902)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:794)
        at com.fasterxml.jackson.jr.ob.JSON._initForReading(JSON.java)
        at com.fasterxml.jackson.jr.ob.JSON.mapFrom(JSON.java)
        at it.mulders.mcs.common.SearchResponseBodyHandler.lambda$toSupplierOfSearchResponse$0(SearchResponseBodyHandler.java:32)
        ... 16 more
```

**Comment by jeffmaury** [comment]
Also add an error with:

`mcs search io.quarkus:quarkus-parent:*`

**Comment by mthmulders** [comment]
I see. There's a difference between your first example (which happens to be a valid query, but mcs didn't pass it correctly) and your second example (which is an invalid query). For the latter case, I've reported #53.

**Comment by mthmulders** [comment]
@all-contributors please add @jeffmaury for bug.
